In [14]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

In [32]:
data = {
    "Name": [
        "Ganesh",
        "Rahul",
        "Priya",
        "Kiran",
        "Anjali",
        "Rohit",
        "Sneha",
        "Arjun",
        "Meena",
        "Vikram"
    ],

    "Age": [
        21,
        24,
        None,
        26,
        22,
        27,
        25,
        None,
        24,
        29
    ],

    "Salary": [
        45000,
        55000,
        50000,
        None,
        48000,
        80000,
        62000,
        90000,
        None,
        95000
    ],

    "Company": [
        "Google",
        "Microsoft",
        "Amazon",
        "Infosys",
        None,
        "Apple",
        "IBM",
        "Meta",
        "Oracle",
        None
    ],
    "Purchased":[
        "yes",
        "no",
        "yes",
        "yes",
        "no",
        "yes",
        "no",
        "yes",
        "no",
        "no"
    ]
}

In [33]:
df = pd.DataFrame(data)

In [34]:
df

     Name   Age   Salary    Company Purchased
0  Ganesh  21.0  45000.0     Google       yes
1   Rahul  24.0  55000.0  Microsoft        no
2   Priya   NaN  50000.0     Amazon       yes
3   Kiran  26.0      NaN    Infosys       yes
4  Anjali  22.0  48000.0       None        no
5   Rohit  27.0  80000.0      Apple       yes
6   Sneha  25.0  62000.0        IBM        no
7   Arjun   NaN  90000.0       Meta       yes
8   Meena  24.0      NaN     Oracle        no
9  Vikram  29.0  95000.0       None        no

In [35]:
dfe = df.copy()

In [36]:
dfe

     Name   Age   Salary    Company Purchased
0  Ganesh  21.0  45000.0     Google       yes
1   Rahul  24.0  55000.0  Microsoft        no
2   Priya   NaN  50000.0     Amazon       yes
3   Kiran  26.0      NaN    Infosys       yes
4  Anjali  22.0  48000.0       None        no
5   Rohit  27.0  80000.0      Apple       yes
6   Sneha  25.0  62000.0        IBM        no
7   Arjun   NaN  90000.0       Meta       yes
8   Meena  24.0      NaN     Oracle        no
9  Vikram  29.0  95000.0       None        no

In [37]:
# imputer from sklearn = it helps in filing the null columns by it self

In [38]:
imputer = SimpleImputer(strategy="mean")

In [39]:
df[["Age", "Salary"]] = imputer.fit_transform(df[["Age", "Salary"]])

In [40]:
df.isnull().sum()

Name         0
Age          0
Salary       0
Company      2
Purchased    0
dtype: int64

In [41]:
df # after

     Name    Age   Salary    Company Purchased
0  Ganesh  21.00  45000.0     Google       yes
1   Rahul  24.00  55000.0  Microsoft        no
2   Priya  24.75  50000.0     Amazon       yes
3   Kiran  26.00  65625.0    Infosys       yes
4  Anjali  22.00  48000.0       None        no
5   Rohit  27.00  80000.0      Apple       yes
6   Sneha  25.00  62000.0        IBM        no
7   Arjun  24.75  90000.0       Meta       yes
8   Meena  24.00  65625.0     Oracle        no
9  Vikram  29.00  95000.0       None        no

In [42]:
df.isnull().sum()

Name         0
Age          0
Salary       0
Company      2
Purchased    0
dtype: int64

In [43]:
dfe# before

     Name   Age   Salary    Company Purchased
0  Ganesh  21.0  45000.0     Google       yes
1   Rahul  24.0  55000.0  Microsoft        no
2   Priya   NaN  50000.0     Amazon       yes
3   Kiran  26.0      NaN    Infosys       yes
4  Anjali  22.0  48000.0       None        no
5   Rohit  27.0  80000.0      Apple       yes
6   Sneha  25.0  62000.0        IBM        no
7   Arjun   NaN  90000.0       Meta       yes
8   Meena  24.0      NaN     Oracle        no
9  Vikram  29.0  95000.0       None        no

In [44]:
df["Purchased"] = df["Purchased"].map({"no":1, "yes":0})

In [45]:
df

     Name    Age   Salary    Company  Purchased
0  Ganesh  21.00  45000.0     Google          0
1   Rahul  24.00  55000.0  Microsoft          1
2   Priya  24.75  50000.0     Amazon          0
3   Kiran  26.00  65625.0    Infosys          0
4  Anjali  22.00  48000.0       None          1
5   Rohit  27.00  80000.0      Apple          0
6   Sneha  25.00  62000.0        IBM          1
7   Arjun  24.75  90000.0       Meta          0
8   Meena  24.00  65625.0     Oracle          1
9  Vikram  29.00  95000.0       None          1

In [49]:
imputer = SimpleImputer(strategy="most_frequent")

In [50]:
df["Company"] = imputer.fit_transform(df["Company"])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.