In [9]:
import pandas as pd

In [4]:
info = {
    "Nmae":["ganesh", "rachana", "sumit", "rakshit"],
    "CGPA":["22", "3","8", "7" ]
}

In [7]:
data = pd.DataFrame(info)

In [10]:
data

      Nmae CGPA
0   ganesh   22
1  rachana    3
2    sumit    8
3  rakshit    7

In [36]:
#Series

In [12]:
s = pd.Series([1,3,4,5,6,7])

In [13]:
s

0    1
1    3
2    4
3    5
4    6
5    7
dtype: int64

In [15]:
#index access
print(s[2])
print(s[5])

4
7

In [25]:
f = pd.Series([1,3,4,5], index=["ganesh", "rachana", "sumit","raksh"])

In [26]:
f

ganesh     1
rachana    3
sumit      4
raksh      5
dtype: int64

In [28]:
#by label access
print(f["ganesh"])
print(f["rachana"])
print(f.index)

1
3
Index(['ganesh', 'rachana', 'sumit', 'raksh'], dtype='object')

In [30]:
g = pd.Series([1,3,4,5,6,7,3,4,4,5])
h = pd.Series([1,3,4,5,6,7,3,4,4,5])

print(g+h)

0     2
1     6
2     8
3    10
4    12
5    14
6     6
7     8
8     8
9    10
dtype: int64

In [31]:
changed = g.drop(0)

In [34]:
changed

1    3
2    4
3    5
4    6
5    7
6    3
7    4
8    4
9    5
dtype: int64

In [35]:
g

0    1
1    3
2    4
3    5
4    6
5    7
6    3
7    4
8    4
9    5
dtype: int64

In [37]:
#dataframes

In [38]:
inform = {
    "Nmae":["ganesh", "rachana", "sumit", "rakshit"],
    "CGPA":["22", "3","8", "7" ]
}

In [39]:
d = pd.DataFrame(inform)

In [47]:
d

      Nmae CGPA
0   ganesh   22
1  rachana    3
2    sumit    8
3  rakshit    7

In [48]:
print(d.index)
print(d.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['Nmae', 'CGPA'], dtype='object')

In [52]:
#list of list
da = pd.DataFrame([["ganesh", 99],["rachana", 99],["sumit", 99],["raksh", 99]], columns=["Name", "Percentage"])

In [53]:
da

      Name  Percentage
0   ganesh          99
1  rachana          99
2    sumit          99
3    raksh          99

In [54]:
#csv

In [57]:
df = pd.read_csv("raw_data_02.csv")

In [58]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [59]:
df = pd.read_json("data.json")

In [60]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [10]:
df = pd.read_csv("globalAirQuality.csv")

In [62]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [63]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [65]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [66]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [76]:
#colunms

In [67]:
df["country"]

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: object

In [69]:
df[["country", "longitude"]]

      country  longitude
0          US    -74.006
1          US    -74.006
2          US    -74.006
3          US    -74.006
4          US    -74.006
...       ...        ...
17995      CH      8.542
17996      CH      8.542
17997      CH      8.542
17998      CH      8.542
17999      CH      8.542

[18000 rows x 2 columns]

In [70]:
# row by loc

In [71]:
df.loc[0] # get the colomns by name not insdex

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [72]:
df.loc[0:2] #here the last 2 also inclused it is inclusive,  get the colomns by index not name

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [75]:
df.iloc[0:2] # here it is exclusive

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [79]:
df.loc[0:2, ["country", "latitude", "temperature" ]]

  country  latitude  temperature
0      US    40.713       18.504
1      US    40.713        5.838
2      US    40.713       31.833

In [81]:
df.iloc[0:2, ["country", "latitude", "temperature" ]]  
#this will give error bcz we can't access ny the name we want to access by index

IndexError: .iloc requires numeric indexers, got ['country' 'latitude' 'temperature']

In [82]:
df.iloc[0:2, 1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006

In [83]:
# see if we change anything in df it will change in original so better pracctice to do .copy() if u are changing

In [84]:
daa = df["country"].copy()

In [85]:
daa

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: object

In [86]:
daa[0] = "vijayapur"

In [87]:
daa # see it is chnaged, for this reason we want to store an copy of that

0        vijayapur
1               US
2               US
3               US
4               US
           ...
17995           CH
17996           CH
17997           CH
17998           CH
17999           CH
Name: country, Length: 18000, dtype: object

In [11]:
#filetring of data

In [12]:
df[df["pm10"] > 108.938]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
29,2025-11-05 23:25:17.554219,US,New York,40.713,-74.006,36.695,121.616,20.502,7.020,34.875,1.090,121,31.469,73.541,5.179
31,2025-11-06 01:25:17.554219,US,New York,40.713,-74.006,27.040,129.462,36.214,4.929,53.409,0.574,129,30.286,66.425,8.910
38,2025-11-06 08:25:17.554219,US,New York,40.713,-74.006,22.522,111.308,25.565,4.773,47.249,0.656,111,31.041,40.447,5.006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17926,2025-11-16 16:25:17.554219,CH,Zurich,47.377,8.542,53.878,110.836,27.563,2.098,41.502,0.523,110,7.368,81.561,3.976
17945,2025-11-17 11:25:17.554219,CH,Zurich,47.377,8.542,20.005,111.345,10.181,6.760,41.602,1.172,111,9.051,50.447,8.624
17963,2025-11-18 05:25:17.554219,CH,Zurich,47.377,8.542,55.755,121.397,50.607,6.284,48.910,1.091,126,8.585,26.913,1.903
17968,2025-11-18 10:25:17.554219,CH,Zurich,47.377,8.542,27.063,143.148,34.420,2.708,44.276,0.565,143,28.369,60.224,0.645
17978,2025-11-18 20:25:17.554219,CH,Zurich,47.377,8.542,33.416,118.201,37.682,3.568,62.881,1.053,118,10.672,31.159,9.848

In [13]:
df[(df["pm10"] > 108.938) & (df["city"] == "New York") ]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
29,2025-11-05 23:25:17.554219,US,New York,40.713,-74.006,36.695,121.616,20.502,7.020,34.875,1.090,121,31.469,73.541,5.179
31,2025-11-06 01:25:17.554219,US,New York,40.713,-74.006,27.040,129.462,36.214,4.929,53.409,0.574,129,30.286,66.425,8.910
38,2025-11-06 08:25:17.554219,US,New York,40.713,-74.006,22.522,111.308,25.565,4.773,47.249,0.656,111,31.041,40.447,5.006
44,2025-11-06 14:25:17.554219,US,New York,40.713,-74.006,78.186,114.005,17.993,5.932,18.151,0.845,156,31.779,49.093,8.211
47,2025-11-06 17:25:17.554219,US,New York,40.713,-74.006,59.945,114.072,27.078,2.843,34.088,0.948,119,11.177,77.287,2.631
64,2025-11-07 10:25:17.554219,US,New York,40.713,-74.006,26.373,111.711,29.563,5.189,47.966,0.722,111,7.049,56.853,4.455
77,2025-11-07 23:25:17.554219,US,New York,40.713,-74.006,46.030,114.838,16.453,3.605,45.076,0.757,114,9.450,72.691,1.629
83,2025-11-08 05:25:17.554219,US,New York,40.713,-74.006,45.648,147.672,30.754,6.384,69.368,1.131,147,22.646,29.746,9.635
103,2025-11-09 01:25:17.554219,US,New York,40.713,-74.006,22.317,112.149,50.515,4.308,43.567,0.875,126,6.048,65.936,0.994
113,2025-11-09 11:25:17.554219,US,New York,40.713,-74.006,22.129,121.261,21.566,4.241,103.016,0.982,121,21.713,52.872,4.386
114,2025-11-09 12:25:17.554219,US,New York,40.713,-74.006,45.299,117.314,39.293,9.391,39.892,1.032,117,15.490,30.634,9.538
122,2025-11-09 20:25:17.554219,US,New York,40.713,-74.006,2.562,111.317,38.457,3.755,53.065,1.116,111,30.123,45.506,6.208
158,2025-11-11 08:25:17.554219,US,New York,40.713,-74.006,22.835,124.933,27.212,8.032,38.089,0.876,124,17.821,49.029,5.599
193,2025-11-12 19:25:17.554219,US,New York,40.713,-74.006,17.688,112.586,18.257,5.669,34.701,0.671,112,15.583,88.651,8.950
203,2025-11-13 05:25:17.554219,US,New York,40.713,-74.006,62.357,109.946,37.236,3.310,45.606,1.045,124,22.328,45.705,1.839
204,2025-11-13 06:25:17.554219,US,New York,40.713,-74.006,17.140,109.137,28.092,12.139,60.609,0.569,109,26.806,30.624,2.154
209,2025-11-13 11:25:17.554219,US,New York,40.713,-74.006,74.786,120.579,67.147,7.620,69.464,0.305,167,13.877,53.443,7.924
225,2025-11-14 03:25:17.554219,US,New York,40.713,-74.006,50.750,117.138,32.574,8.172,50.872,0.769,117,29.839,25.870,3.963
229,2025-11-14 07:25:17.554219,US,New York,40.713,-74.006,6.845,143.311,37.462,8.311,33.774,0.640,143,34.490,40.955,3.728
239,2025-11-14 17:25:17.554219,US,New York,40.713,-74.006,39.413,117.291,25.233,4.823,63.738,0.596,117,25.997,37.562,5.904
240,2025-11-14 18:25:17.554219,US,New York,40.713,-74.006,56.655,114.617,29.837,6.351,41.892,1.018,114,35.021,29.741,5.826
268,2025-11-15 22:25:17.554219,US,New York,40.713,-74.006,39.891,120.792,30.567,6.665,16.721,0.824,120,32.465,61.898,8.150
273,2025-11-16 03:25:17.554219,US,New York,40.713,-74.006,12.903,120.485,7.850,4.275,46.907,0.833,120,23.521,68.260,8.585
323,2025-11-18 05:25:17.554219,US,New York,40.713,-74.006,41.092,118.504,29.033,6.803,61.477,0.840,118,16.573,89.107,4.670
335,2025-11-18 17:25:17.554219,US,New York,40.713,-74.006,39.031,122.708,46.391,5.796,40.510,0.281,122,17.674,78.201,2.528

In [14]:
df[(df["pm10"] > 108.938) | (df["city"] == "New York") ]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17926,2025-11-16 16:25:17.554219,CH,Zurich,47.377,8.542,53.878,110.836,27.563,2.098,41.502,0.523,110,7.368,81.561,3.976
17945,2025-11-17 11:25:17.554219,CH,Zurich,47.377,8.542,20.005,111.345,10.181,6.760,41.602,1.172,111,9.051,50.447,8.624
17963,2025-11-18 05:25:17.554219,CH,Zurich,47.377,8.542,55.755,121.397,50.607,6.284,48.910,1.091,126,8.585,26.913,1.903
17968,2025-11-18 10:25:17.554219,CH,Zurich,47.377,8.542,27.063,143.148,34.420,2.708,44.276,0.565,143,28.369,60.224,0.645
17978,2025-11-18 20:25:17.554219,CH,Zurich,47.377,8.542,33.416,118.201,37.682,3.568,62.881,1.053,118,10.672,31.159,9.848

In [15]:
df[(df["pm10"] > 108.938) & (df["city"] == "New York")][["city", "country"]]

         city country
7    New York      US
14   New York      US
29   New York      US
31   New York      US
38   New York      US
44   New York      US
47   New York      US
64   New York      US
77   New York      US
83   New York      US
103  New York      US
113  New York      US
114  New York      US
122  New York      US
158  New York      US
193  New York      US
203  New York      US
204  New York      US
209  New York      US
225  New York      US
229  New York      US
239  New York      US
240  New York      US
268  New York      US
273  New York      US
323  New York      US
335  New York      US

In [16]:
#query

In [21]:
df.query("pm10 > 100 ")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
20,2025-11-05 14:25:17.554219,US,New York,40.713,-74.006,22.220,102.306,37.332,5.142,32.491,0.781,102,12.790,65.872,7.227
29,2025-11-05 23:25:17.554219,US,New York,40.713,-74.006,36.695,121.616,20.502,7.020,34.875,1.090,121,31.469,73.541,5.179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17933,2025-11-16 23:25:17.554219,CH,Zurich,47.377,8.542,26.961,101.276,56.111,7.191,51.238,0.444,140,9.986,37.198,0.933
17945,2025-11-17 11:25:17.554219,CH,Zurich,47.377,8.542,20.005,111.345,10.181,6.760,41.602,1.172,111,9.051,50.447,8.624
17963,2025-11-18 05:25:17.554219,CH,Zurich,47.377,8.542,55.755,121.397,50.607,6.284,48.910,1.091,126,8.585,26.913,1.903
17968,2025-11-18 10:25:17.554219,CH,Zurich,47.377,8.542,27.063,143.148,34.420,2.708,44.276,0.565,143,28.369,60.224,0.645
17978,2025-11-18 20:25:17.554219,CH,Zurich,47.377,8.542,33.416,118.201,37.682,3.568,62.881,1.053,118,10.672,31.159,9.848

In [22]:
#cleaning of data

In [23]:
data = pd.read_csv("raw_data_02.csv")

In [24]:
data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [26]:
data.isnull()  # or data.isna()    this also gove the same thing

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [29]:
#using chainn 
data.isna().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [30]:
drop_data = data.dropna()

In [31]:
drop_data

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [32]:
fill_data = data.fillna(0)

In [33]:
fill_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [37]:
clean_data = data.copy()
age_mean = clean_data["age"].mean()
clean_data["age"]=clean_data["age"].fillna(age_mean)

In [38]:
clean_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [42]:
data["age"].ffill()

0     29.0
1     29.0
2     29.0
3     29.0
4     34.0
5     27.0
6     45.0
7     38.0
8     29.0
9     29.0
10    31.0
Name: age, dtype: float64

In [43]:
data["age"].bfill()

0     29.0
1     29.0
2     34.0
3     34.0
4     34.0
5     27.0
6     45.0
7     38.0
8     29.0
9     31.0
10    31.0
Name: age, dtype: float64

In [44]:
#Hanmdle dublicate

In [49]:
data.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [50]:
data["gender"].duplicated()

0     False
1      True
2     False
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10    False
Name: gender, dtype: bool

In [51]:
data[["gender", "country"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [55]:
data.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [56]:
#handle string

In [58]:
# Handle Data Types

df = 

df.dtypes                                     # dtype of each col
df2 = df.fillna(0).copy()
df2["age"] = df2["age"].astype(int)       # change dtype

# String type
df2["gender"].str.lower()                      # lower case
df2["gender"].str.upper()                      # upper case
df2["gender"].str.capitalize()                 # capitalize

df2["gender"].str.capitalize()                 # capitalize
df2["name"].str.split(" ")                     # splits into lists based on separator value 
type(df2["name"].str.split(" ")[0])            

df2["country"].str.contains("US")
df2["country"].str.contains("india", case=False)

KeyError: 'age'