In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data_02.csv")

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
dfe = df.copy()

In [8]:
dfe.columns = ["ID", "NAME","AGE", "COUNTRY", "GENDER", "INCOME"]

In [9]:
dfe.columns

Index(['ID', 'NAME', 'AGE', 'COUNTRY', 'GENDER', 'INCOME'], dtype='object')

In [10]:
dfe

    ID          NAME   AGE COUNTRY   GENDER   INCOME
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [11]:
dfe.index

RangeIndex(start=0, stop=11, step=1)

In [12]:
info = {
"Name" : ["Adam", "Eve", "Bob"],
"Marks" : [78, 99, 85],
"Grade" : ['B', 'O', 'A']
}
pd.DataFrame(info)

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A

In [13]:
dfe.head()

   ID          NAME   AGE COUNTRY   GENDER   INCOME
0   1      John Doe  29.0     USA     Male  55000.0
1   1      John Doe  29.0     USA     Male  55000.0
2   2    Jane Smith   NaN  Canada   Female  62000.0
3   3          Alex   NaN     USA  Unknown  47000.0
4   4  Maria Garcia  34.0   Spain   Female      NaN

In [14]:
dfe.tail()

    ID         NAME   AGE COUNTRY  GENDER   INCOME
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
8    8   Rachel Lee  29.0     USA  Female  62000.0
9    9  Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [19]:
dfe.sample(8)

    ID         NAME   AGE COUNTRY   GENDER   INCOME
3    3         Alex   NaN     USA  Unknown  47000.0
6    6          NaN  45.0   India   Female  73000.0
8    8   Rachel Lee  29.0     USA   Female  62000.0
1    1     John Doe  29.0     USA     Male  55000.0
9    9  Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10  Emily Davis  31.0     USA      NaN  58000.0
2    2   Jane Smith   NaN  Canada   Female  62000.0
5    5       Li Wei  27.0   China     Male  51000.0

In [20]:
dfe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       11 non-null     int64
 1   NAME     10 non-null     object
 2   AGE      8 non-null      float64
 3   COUNTRY  10 non-null     object
 4   GENDER   10 non-null     object
 5   INCOME   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes

In [24]:
dfe.describe()

              ID        AGE        INCOME
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [22]:
dfe.nunique()

ID         10
NAME        9
AGE         6
COUNTRY     6
GENDER      3
INCOME      8
dtype: int64

In [25]:
#Indexing & Data Selection

In [29]:
dfe["COUNTRY"]

0        USA
1        USA
2     Canada
3        USA
4      Spain
5      China
6      India
7        NaN
8        USA
9     Mexico
10       USA
Name: COUNTRY, dtype: object

In [31]:
dfe[["COUNTRY", "AGE", "INCOME"]]

   COUNTRY   AGE   INCOME
0      USA  29.0  55000.0
1      USA  29.0  55000.0
2   Canada   NaN  62000.0
3      USA   NaN  47000.0
4    Spain  34.0      NaN
5    China  27.0  51000.0
6    India  45.0  73000.0
7      NaN  38.0  68000.0
8      USA  29.0  62000.0
9   Mexico   NaN  45000.0
10     USA  31.0  58000.0

In [35]:
dfe.loc[0]

ID                1
NAME       John Doe
AGE            29.0
COUNTRY         USA
GENDER         Male
INCOME      55000.0
Name: 0, dtype: object

In [36]:
dfe.loc[0, ["COUNTRY", "AGE"]]

COUNTRY     USA
AGE        29.0
Name: 0, dtype: object

In [37]:
dfe.loc[0:3, ["COUNTRY", "AGE"]]

  COUNTRY   AGE
0     USA  29.0
1     USA  29.0
2  Canada   NaN
3     USA   NaN

In [38]:
dfe.iloc[0]

ID                1
NAME       John Doe
AGE            29.0
COUNTRY         USA
GENDER         Male
INCOME      55000.0
Name: 0, dtype: object

In [40]:
dfe.iloc[0:3, 0:6]

   ID        NAME   AGE COUNTRY  GENDER   INCOME
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
2   2  Jane Smith   NaN  Canada  Female  62000.0

In [41]:
#Filtering & Querying Data

In [43]:
dfe[dfe["AGE"] > 16]

    ID          NAME   AGE COUNTRY  GENDER   INCOME
0    1      John Doe  29.0     USA    Male  55000.0
1    1      John Doe  29.0     USA    Male  55000.0
4    4  Maria Garcia  34.0   Spain  Female      NaN
5    5        Li Wei  27.0   China    Male  51000.0
6    6           NaN  45.0   India  Female  73000.0
7    7    Ahmed Khan  38.0     NaN    Male  68000.0
8    8    Rachel Lee  29.0     USA  Female  62000.0
10  10   Emily Davis  31.0     USA     NaN  58000.0

In [44]:
dfe[(dfe["AGE"] > 3) & (dfe["INCOME"] > 50000)]

    ID         NAME   AGE COUNTRY  GENDER   INCOME
0    1     John Doe  29.0     USA    Male  55000.0
1    1     John Doe  29.0     USA    Male  55000.0
5    5       Li Wei  27.0   China    Male  51000.0
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
8    8   Rachel Lee  29.0     USA  Female  62000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [ ]:
#2. We can use operators like and, or ,  not, !=, == ,>= ,<= , , etc.

In [47]:
dfe.query("AGE > 29 & INCOME >  50000")

    ID         NAME   AGE COUNTRY  GENDER   INCOME
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [49]:
salary = 50000
dfe.query("AGE > 29 and INCOME >  @salary")

    ID         NAME   AGE COUNTRY  GENDER   INCOME
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [50]:
salary = 50000
dfe.query("AGE > 29 or INCOME >  @salary")

    ID          NAME   AGE COUNTRY  GENDER   INCOME
0    1      John Doe  29.0     USA    Male  55000.0
1    1      John Doe  29.0     USA    Male  55000.0
2    2    Jane Smith   NaN  Canada  Female  62000.0
4    4  Maria Garcia  34.0   Spain  Female      NaN
5    5        Li Wei  27.0   China    Male  51000.0
6    6           NaN  45.0   India  Female  73000.0
7    7    Ahmed Khan  38.0     NaN    Male  68000.0
8    8    Rachel Lee  29.0     USA  Female  62000.0
10  10   Emily Davis  31.0     USA     NaN  58000.0

In [53]:
salary = 50000
dfe.query("AGE > 19 == INCOME >  @salary")

Empty DataFrame
Columns: [ID, NAME, AGE, COUNTRY, GENDER, INCOME]
Index: []

In [56]:
dfe.query("AGE == 29")

   ID        NAME   AGE COUNTRY  GENDER   INCOME
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [61]:
va = "USA"
dfe.query("AGE != 29 and COUNTRY == @va")

    ID         NAME   AGE COUNTRY   GENDER   INCOME
3    3         Alex   NaN     USA  Unknown  47000.0
10  10  Emily Davis  31.0     USA      NaN  58000.0